// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHAs49N0Hu-kEJA3fVTCWPgVFKGUDli-o',
    appId: '1:905479752530:web:c3dd029c79b0d12110888b',
    messagingSenderId: '905479752530',
    projectId: 'todo-mini-2910d',
    authDomain: 'todo-mini-2910d.firebaseapp.com',
    storageBucket: 'todo-mini-2910d.firebasestorage.app',
    measurementId: 'G-LYM5MVE3HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoh5vsce6Ir_SNMLMm891rm6-GPMMyn5I',
    appId: '1:905479752530:android:f50ec6acb7d3abf910888b',
    messagingSenderId: '905479752530',
    projectId: 'todo-mini-2910d',
    storageBucket: 'todo-mini-2910d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-PPfUQWPzxqqh1OncrwpNgJXWmrdqRco',
    appId: '1:905479752530:ios:6e85f1f93302847b10888b',
    messagingSenderId: '905479752530',
    projectId: 'todo-mini-2910d',
    storageBucket: 'todo-mini-2910d.firebasestorage.app',
    iosClientId: '905479752530-esi3nvodcfliupn016p09b69830lkqrn.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoMini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-PPfUQWPzxqqh1OncrwpNgJXWmrdqRco',
    appId: '1:905479752530:ios:6e85f1f93302847b10888b',
    messagingSenderId: '905479752530',
    projectId: 'todo-mini-2910d',
    storageBucket: 'todo-mini-2910d.firebasestorage.app',
    iosClientId: '905479752530-esi3nvodcfliupn016p09b69830lkqrn.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoMini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHAs49N0Hu-kEJA3fVTCWPgVFKGUDli-o',
    appId: '1:905479752530:web:0aa8275b5b7cd15910888b',
    messagingSenderId: '905479752530',
    projectId: 'todo-mini-2910d',
    authDomain: 'todo-mini-2910d.firebaseapp.com',
    storageBucket: 'todo-mini-2910d.firebasestorage.app',
    measurementId: 'G-NJ8ZHDSJFQ',
  );
}
